### ISSUE TITLE
dimensional-1.6 failed to build with ghc-9.8.3

### ISSUE THREAD

**Issue by juhp** [bjornbm/dimensional#228]
For Stackage Nightly:

```
       Building library for dimensional-1.6..                                                                                       
       [ 8 of 18] Compiling Numeric.Units.Dimensional.Internal                                                                      
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/dimensional-1.6-8efe22e508b9f12f66a8baf45608acefbc406643f68ea74219a7b38fca8576d9/src/
Numeric/Units/Dimensional/Internal.hs:109:17: error: [GHC-87543]                                                                    
           Ambiguous occurrence ‘Unit’.                                                                                             
           It could refer to                                                                                                        
              either ‘Control.DeepSeq.Unit’,                                                                                        
                     imported from ‘Control.DeepSeq’ at src/Numeric/Units/Dimensional/Internal.hs:29:1-22,                          
                  or ‘Numeric.Units.Dimensional.Internal.Unit’,                                                                     
                     defined at src/Numeric/Units/Dimensional/Internal.hs:106:37.                                                   
           |                                                                                                                        
       109 |   extractValue (Unit _ e x) = (x, Just e)                                                                              
           |                 ^^^^                                                                                                   
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/dimensional-1.6-8efe22e508b9f12f66a8baf45608acefbc406643f68ea74219a7b38fca8576d9/src/
Numeric/Units/Dimensional/Internal.hs:110:16: error: [GHC-87543]
           Ambiguous occurrence ‘Unit’.                           
           It could refer to                                                                                                        
              either ‘Control.DeepSeq.Unit’,       
                     imported from ‘Control.DeepSeq’ at src/Numeric/Units/Dimensional/Internal.hs:29:1-22,                          
                  or ‘Numeric.Units.Dimensional.Internal.Unit’,   
                     defined at src/Numeric/Units/Dimensional/Internal.hs:106:37.                                                   
           |                                                                                                                        
       110 |   extractName (Unit n _ _) = Just . Name.weaken $ n                                                                    
           |                ^^^^
                                
       /home/curators/work/unpack-dir/unpacked/dimensional-1.6-8efe22e508b9f12f66a8baf45608acefbc406643f68ea74219a7b38fca8576d9/src/
Numeric/Units/Dimensional/Internal.hs:111:59: error: [GHC-87543]  
           Ambiguous occurrence ‘Unit’.                           
           It could refer to                                                                                                        
              either ‘Control.DeepSeq.Unit’,                                                                                        
                     imported from ‘Control.DeepSeq’ at src/Numeric/Units/Dimensional/Internal.hs:29:1-22,
                  or ‘Numeric.Units.Dimensional.Internal.Unit’,
                     defined at src/Numeric/Units/Dimensional/Internal.hs:106:37.
           |
       111 |   injectValue (Just n) (x, Just e) | Just n' <- relax n = Unit n' e x
           |                                                           ^^^^
```

**Comment by LaurentRDC** [comment]
I'll be able to take a look today

**Comment by LaurentRDC** [comment]
I have published Hackage revisions to prevent building dimensional with deepseq-1.5.1.0 in the meantime.

@bjornbm Do you mind if I alter the versioning scheme to publish version 1.6.1 (rather than 1.7)?

**Comment by bjornbm** [comment]
@LaurentRDC sure! Sorry for the delay and thanks for taking care if this!

**Comment by LaurentRDC** [comment]
@juhp [dimensional-1.6.1](https://hackage.haskell.org/package/dimensional-1.6.1) was just released, and allows deepseq 1.5.1.0+
